version: "3.7"
services:
  container-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    #If needed, network mode to host e.g. when awaiting responses to request and running on public server
    #network_mode: "host"
    #If needed, expose external port
    #ports:
    #  - ${EXT_PORT}:${EXT_PORT}
    #Directly attach working dir to container
    #volumes:
    #  - ./app:/code/
    
    #If needed, let container restart infinitely
    #restart: unless-stopped
    env_file: .env
